/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testdb;

import javafx.application.Application;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.scene.text.Font;
import javafx.stage.Stage;
import testdb.dao.StudentDao;
import testdb.models.Student;
import java.sql.SQLException;
import java.util.ArrayList;

public class App extends Application {
    private TableView<Student> table;
    private ObservableList<Student> data = FXCollections.observableArrayList();
    private StudentDao studentDao;

    @Override
    public void start(Stage stage) {
        try {
            studentDao = new StudentDao();
            data.addAll(studentDao.readDb());
        } catch (SQLException e) {
        }
        setUpTable();

        final Label label = new Label("Aplikasi Pencatat Nickname");
        label.setFont(new Font("Arial", 20));

        final TextField tfName = new TextField();
        tfName.setPromptText("Nama");
        tfName.setMaxWidth(100);
        final TextField tfNim = new TextField();
        tfNim.setMaxWidth(100);
        tfNim.setPromptText("NIM");
        final TextField tfNickName = new TextField();
        tfNickName.setMaxWidth(100);
        tfNickName.setPromptText("NickName");

        final Button btnAdd = new Button("Tambah");
        btnAdd.setOnAction(v -> {
            data.add(new Student(tfName.getText(), tfNim.getText(), tfNickName.getText()));
            tfName.clear();
            tfNim.clear();
            tfNickName.clear();
        });

        HBox hBox = new HBox(tfName, tfNim, tfNickName, btnAdd);

        Button btnSinc = new Button("Sinkronisasi");
        btnSinc.setPrefWidth(300);
        btnSinc.setOnAction(v -> {
            studentDao.synchronizeDb(new ArrayList<>(data));
        });

        final VBox vbox = new VBox();
        vbox.setSpacing(5);
        vbox.setAlignment(Pos.CENTER);
        vbox.setPadding(new Insets(10, 0, 0, 10));
        vbox.getChildren().addAll(label, table, hBox, btnSinc);

        Scene scene = new Scene(new Group(vbox));
        stage.setTitle("Aplikasi Pencatat Nickname");
        stage.setWidth(400);
        stage.setHeight(600);
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        launch();
    }

    private void setUpTable() {
        table = new TableView<>();
        table.setEditable(true);
        TableColumn<Student, String> fullName = new TableColumn<>("Nama");
        fullName.setMinWidth(120);
        fullName.setMaxWidth(120);

        TableColumn<Student, String> id = new TableColumn<>("NIM");
        id.setMinWidth(100);
        id.setMaxWidth(100);

        TableColumn<Student, String> nickName = new TableColumn<>("Nick Name");
        nickName.setMinWidth(100);
        nickName.setMaxWidth(100);

        fullName.setCellValueFactory(new PropertyValueFactory<>("fullname"));
        id.setCellValueFactory(new PropertyValueFactory<>("nim"));
        nickName.setCellValueFactory(new PropertyValueFactory<>("nickname"));
        table.getColumns().addAll(fullName, id, nickName);
        table.setItems(data);
    }

}