/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package helloapp;

import helloapp.helpers.AppColor;
import helloapp.models.Bmi;
import javafx.application.Application;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.image.ImageView;
import javafx.scene.layout.HBox;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.scene.text.TextAlignment;
import javafx.stage.Stage;

public class App extends Application {
    private Stage mainStage;

    @Override
    public void start(Stage stage) {
        mainStage = stage;
        mainStage.setScene(showMainScene());
        mainStage.setResizable(false);
        mainStage.show();
    }

    public static void main(String[] args) {
        launch();
    }

    private Bmi calculateBmi(double height, double weight) {
        // Colors
        height = height / 100;
        Bmi bmi = new Bmi();
        bmi.setBmi(weight / (height * height));
        if (bmi.getBmi() < 18.5) {
            bmi.setCategory("Berat Kurang");
            bmi.setColor(AppColor.YELLOW);
        } else if (bmi.getBmi() < 25) {
            bmi.setCategory("Berat Normal");
            bmi.setColor(AppColor.GREEN);
        } else if (bmi.getBmi() < 30) {
            bmi.setCategory("Berat Berlebih");
            bmi.setColor(AppColor.YELLOW);
        } else if (bmi.getBmi() < 35) {
            bmi.setCategory("Obesitas (kelas 1)");
            bmi.setColor(AppColor.RED);
        } else if (bmi.getBmi() < 40) {
            bmi.setCategory("Obesitas (kelas 2)");
            bmi.setColor(AppColor.RED);
        } else {
            bmi.setCategory("Obesitas (kelas 3)");
            bmi.setColor(AppColor.RED);
        }
        return bmi;
    }

    private Scene showDetailScene(double height, double weight) {
        Bmi bmi = calculateBmi(height, weight);
        Label lTitle = new Label("Your BMI calculation results");

        Label lBmi = new Label(String.format("%.2f", bmi.getBmi()));
        lBmi.setId("lBmi");

        Label lResult = new Label(bmi.getCategory());
        lResult.setWrapText(true);
        lResult.setTextAlignment(TextAlignment.CENTER);
        lResult.setId("lResult");

        Button btnBack = new Button("Back to Home");

        VBox vBottom = new VBox();
        vBottom.setId("vResult");
        vBottom.getChildren().addAll(lBmi, lResult);
        vBottom.setStyle("-fx-background-color: " + bmi.getColor());
        vBottom.setAlignment(Pos.CENTER);

        VBox vMain = new VBox(16);
        vMain.setPrefWidth(320);
        vMain.getChildren().addAll(lTitle, vBottom, btnBack);
        vMain.setAlignment(Pos.CENTER);

        ImageView imageView = new ImageView("/images/bg.png");
        imageView.setPreserveRatio(false);
        imageView.setFitWidth(320);

        HBox hBox = new HBox();
        hBox.getChildren().add(imageView);
        hBox.getChildren().add(vMain);

        StackPane pane = new StackPane(hBox);
        Scene scene = new Scene(pane, 640, 480);
        scene.getStylesheets()
                .add(getClass()
                        .getResource("/styles/style.css")
                        .toExternalForm());

        btnBack.setOnAction(v -> {
            mainStage.setScene(showMainScene());
        });

        return scene;
    }

    private Scene showMainScene() {
        Label lTitle = new Label("BMI App");
        lTitle.setId("title");
        Label lHeight = new Label("Height (cm)");
        TextField tfHeight = new TextField();
        Label lWeight = new Label("Weight (kg)");
        TextField tfWeight = new TextField();
        Button btnSubmit = new Button("Calculate BMI");

        VBox vBottom = new VBox(8);
        vBottom.setId("vBottom");
        vBottom.getChildren().addAll(lHeight, tfHeight, lWeight, tfWeight);

        VBox vMain = new VBox(16);
        vMain.setPrefWidth(320);
        vMain.getChildren().addAll(lTitle, vBottom, btnSubmit);
        vMain.setAlignment(Pos.CENTER);

        ImageView imageView = new ImageView("/images/bg.png");
        imageView.setPreserveRatio(false);
        imageView.setFitWidth(320);

        HBox hBox = new HBox();
        hBox.getChildren().add(imageView);
        hBox.getChildren().add(vMain);

        StackPane pane = new StackPane(hBox);

        Scene scene = new Scene(pane, 640, 480);
        scene.getStylesheets().add(getClass().getResource("/styles/style.css").toExternalForm());

        //
        btnSubmit.setOnAction(v -> {
            double weight = Double.parseDouble(tfWeight.getText());
            double height = Double.parseDouble(
                    tfHeight.getText());
            mainStage.setScene(showDetailScene(height, weight));
        });
        return scene;
    }
}